DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE THEME_LIST CASCADE CONSTRAINTS;
--DROP TABLE THEME CASCADE CONSTRAINTS;
--DROP TABLE REPLY CASCADE CONSTRAINTS;
DROP TABLE THEME_FILES CASCADE CONSTRAINTS;
DROP TABLE THEME_LIKES CASCADE CONSTRAINTS;
DROP TABLE THEME_REPLY CASCADE CONSTRAINTS;
DROP TABLE THEME_CODE CASCADE CONSTRAINTS;
DROP TABLE BLOG_LIST CASCADE CONSTRAINTS;
DROP TABLE BLOG_FILES CASCADE CONSTRAINTS;
DROP TABLE BLOG_REPLY CASCADE CONSTRAINTS;
DROP TABLE REPORTS CASCADE CONSTRAINTS;
DROP TABLE RECOMMEND_Q CASCADE CONSTRAINTS;
DROP TABLE QNA CASCADE CONSTRAINTS;

--CREATE USER ALIGO IDENTIFIED BY ALIGO;
--GRANT RESOURCE, CONNECT, CREATE VIEW TO ALIGO;

DROP SEQUENCE SEQ_TNO;
DROP SEQUENCE SEQ_MNO;
DROP SEQUENCE SEQ_QID;

CREATE SEQUENCE SEQ_QID
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;


CREATE SEQUENCE SEQ_TNO
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

CREATE SEQUENCE SEQ_MNO
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

CREATE TABLE THEME_CODE(
   TCODE VARCHAR2(4) PRIMARY KEY,
   TNAME VARCHAR2(500)
);

CREATE TABLE MEMBER(
 MID VARCHAR2(10) PRIMARY KEY,
 EMAIL VARCHAR2(50),
 PASSWORD VARCHAR2(40),
 NICKNAME VARCHAR2(50),
 GENDER VARCHAR2(2) CHECK (GENDER IN('M','F')),
 AGE NUMBER,
 M_STATUS VARCHAR2(2) DEFAULT 'Y' CHECK (M_STATUS IN('Y','N')),
 RECOMMEND VARCHAR2(3000)
);

CREATE TABLE THEME_LIST(
  TID NUMBER PRIMARY KEY, 
  TWRITER VARCHAR2(15) DEFAULT 'ADMIN',
  TTITLE VARCHAR2(300) NOT NULL,
  TCONTENT VARCHAR2(4000) NOT NULL,
  TADDRESS VARCHAR2(1000) NOT NULL,
  T_CREATE_DATE DATE DEFAULT SYSDATE,
  T_MODIFY_DATE DATE DEFAULT SYSDATE,
  T_VIEWS NUMBER DEFAULT 0,
  T_LIKES NUMBER DEFAULT 0,
  TKEYWORD VARCHAR2(3000),
  T_STATUS VARCHAR2(5) DEFAULT 'Y' CHECK (T_STATUS IN('Y','N','X')),
  TCODE VARCHAR2(4) REFERENCES THEME_CODE ON DELETE CASCADE
);

CREATE TABLE THEME_FILES(
   T_CODE_NUMBER NUMBER REFERENCES THEME_LIST ON DELETE CASCADE,
   T_ORIGINAL_FILE VARCHAR2(100),
   T_MODIFY_FILE VARCHAR2(100)
);

CREATE TABLE THEME_LIKES(
  MID VARCHAR2(50) REFERENCES MEMBER ON DELETE CASCADE,
  T_CODE_NUM NUMBER REFERENCES THEME_LIST ON DELETE CASCADE
);

CREATE TABLE THEME_REPLY(
  TRNUM NUMBER,
  T_CODE_NUMBER NUMBER,
  TR_WRITER VARCHAR2(50),
  TR_CONTENT VARCHAR2(3000),
  TR_STATUS VARCHAR2(5) DEFAULT 'Y' CHECK (TR_STATUS IN('Y','N'))
);

--CREATE TABLE REPLY(
--RID NUMBER, --PRIMARY KEY
--RCONTENT VARCHAR2(500),
--REF_BID NUMBER,
--RWRITER VARCHAR2(40),
--R_CREATE_DATE DATE DEFAULT SYSDATE,
--R_MODIFY_DATE DATE DEFAULT SYSDATE,
--R_STATUS VARCHAR2(5) DEFAULT 'Y' CHECK(R_STATUS('Y','N'))
--SPRING DB¿« MODEL ¬¸¡∂

--);

CREATE TABLE BLOG_LIST(
 BID NUMBER PRIMARY KEY,
 BWRITER VARCHAR2(15) DEFAULT 'ADMIN',
 BTITLE VARCHAR2(300) NOT NULL,
 BCONTENT VARCHAR2(3000) NOT NULL,
 BADDRESS VARCHAR2(1000) NOT NULL,
  B_CREATE_DATE DATE DEFAULT SYSDATE,
  B_MODIFY_DATE DATE DEFAULT SYSDATE,
  BCOUNT NUMBER DEFAULT 0,
  BLIKED NUMBER DEFAULT 0,
  BTAG VARCHAR2(3000),
  BSTATUS VARCHAR2(5) DEFAULT 'Y' CHECK(BSTATUS IN('Y','N'))
);   

CREATE TABLE BLOG_FILES(
  BCODE_NUMBER NUMBER REFERENCES BLOG_LIST ON DELETE CASCADE,
  B_ORIGIN_FILE VARCHAR2(1000),
  B_MODIFY_FILE VARCHAR2(1000)  
);

CREATE TABLE BLOG_REPLY(
  BRNUM NUMBER,
  BCODE_NUMBER NUMBER,
  BR_WRITER VARCHAR2(50),
  BR_CONTENT VARCHAR2(3000),
  BR_STATUS VARCHAR2(5) DEFAULT 'Y' CHECK(BR_STATUS IN('Y','N'))
);

CREATE TABLE REPORTS(
  RCODE VARCHAR2(5),
  DCODE_NUMBER NUMBER,
  REPORTER VARCHAR2(50),
  REPORT_CONTENT VARCHAR2(1000),
  REPORT_SDATE DATE,
  REPORT_EDATE DATE,
  R_STATUS VARCHAR2(5) DEFAULT 'Y' CHECK(R_STATUS IN('Y','N','X'))
);

CREATE TABLE RECOMMEND_Q(
 RQCODE VARCHAR2(300),
 RQCONTENT VARCHAR2(3000),
 RQKEYWORD1 VARCHAR2(500),
 KEYWORD1_CONTENT VARCHAR2(300),
 RQKEYWORD2 VARCHAR2(500),
 KEYWROD2_CONTENT VARCHAR2(300) 
);

--THEME_LIST ≈◊Ω∫∆ÆøÎ THEME_CODE ∏’¿˙ ¿‘∑¬«ÿæﬂ«‘ 
INSERT INTO THEME_CODE VALUES('T1','HISTORY');
INSERT INTO THEME_CODE VALUES('T2','FOOD');
INSERT INTO THEME_CODE VALUES('T3','SHOPPING');
INSERT INTO THEME_CODE VALUES('T4','FESTIVE');
INSERT INTO THEME_CODE VALUES('T5','NIGHT VIEW SCENERY');
INSERT INTO THEME_CODE VALUES('T6','MUSEUM');
INSERT INTO THEME_CODE VALUES('T7','EXOTIC');


INSERT INTO THEME_LIST VALUES(SEQ_TNO.NEXTVAL,DEFAULT,'TEST01','≈◊Ω∫∆Æ1¿‘¥œ¥Ÿ','∞≠≥≤','2020/04/04','2020/04/04',DEFAULT,DEFAULT,'ºÓ«Œ',DEFAULT,'T3');
INSERT INTO THEME_LIST VALUES(SEQ_TNO.NEXTVAL,DEFAULT,'TEST02','≈◊Ω∫∆Æ2¿‘¥œ¥Ÿ','±§¿ÂΩ√¿Â','2019/10/10','2019/10/10',DEFAULT,DEFAULT,'ø™ªÁ',DEFAULT,'T1');
INSERT INTO THEME_LIST VALUES(SEQ_TNO.NEXTVAL,DEFAULT,'TEST03','≈◊Ω∫∆Æ3¿‘¥œ¥Ÿ','∏Ìµø','2019/11/11','2019/11/11',DEFAULT,DEFAULT,'∏‘πÊ ¿ΩΩƒ',DEFAULT,'T2');
INSERT INTO THEME_LIST VALUES(SEQ_TNO.NEXTVAL,DEFAULT,'TEST04','≈◊Ω∫∆Æ4¿‘¥œ¥Ÿ','µø¥ÎπÆ','2019/12/12','2019/12/12',DEFAULT,DEFAULT,'√‡¡¶ ∞¯ø¨',DEFAULT,'T4');
INSERT INTO THEME_LIST VALUES(SEQ_TNO.NEXTVAL,DEFAULT,'TEST05','≈◊Ω∫∆Æ5¿‘¥œ¥Ÿ','ªÔ√ªµø','2020/01/01','2020/01/01',DEFAULT,DEFAULT,'æﬂ∞Ê ∞Êƒ°',DEFAULT,'T5');
INSERT INTO THEME_LIST VALUES(SEQ_TNO.NEXTVAL,DEFAULT,'TEST06','≈◊Ω∫∆Æ6¿‘¥œ¥Ÿ','¿Ã√Ã','2020/02/02','2020/02/02',DEFAULT,DEFAULT,'π⁄π∞∞¸ Ω«≥ª',DEFAULT,'T6');
INSERT INTO THEME_LIST VALUES(SEQ_TNO.NEXTVAL,DEFAULT,'TEST07','≈◊Ω∫∆Æ7¿‘¥œ¥Ÿ','≥≤ªÍ','2020/03/03','2020/03/03',DEFAULT,DEFAULT,'¿Ã±π¿˚¿Œ ∏≈∑¬¿˚¿Œ',DEFAULT,'T7');
INSERT INTO THEME_LIST VALUES(SEQ_TNO.NEXTVAL,DEFAULT,'TEST08','≈◊Ω∫∆Æ8¿‘¥œ¥Ÿ','∫œ«—ªÍ','2019/05/05','2019/05/05',DEFAULT,DEFAULT,'∞Êƒ° ¥‹«≥',DEFAULT,'T7');
INSERT INTO THEME_LIST VALUES(SEQ_TNO.NEXTVAL,DEFAULT,'TEST09','≈◊Ω∫∆Æ9¿‘¥œ¥Ÿ','∫ŒªÍ','2019/06/06','2019/06/06',DEFAULT,DEFAULT,'æﬂ∞Ê µµΩ√',DEFAULT,'T5');
INSERT INTO THEME_LIST VALUES(SEQ_TNO.NEXTVAL,DEFAULT,'TEST10','≈◊Ω∫∆Æ10¿‘¥œ¥Ÿ','∞Ê»Ò∑Á','2019/07/07','2019/07/07',DEFAULT,DEFAULT,'∞Êƒ° ¿Ã±π¿˚¿Œ',DEFAULT,'T7');
INSERT INTO THEME_LIST VALUES(SEQ_TNO.NEXTVAL,DEFAULT,'TEST11','≈◊Ω∫∆Æ11¿‘¥œ¥Ÿ','¡¶¡÷ √µ¡ˆø¨ ∆¯∆˜','2019/08/08','2019/08/08',DEFAULT,DEFAULT,'∞Êƒ°',DEFAULT,'T7');
INSERT INTO THEME_LIST VALUES(SEQ_TNO.NEXTVAL,DEFAULT,'TEST12','≈◊Ω∫∆Æ12¿‘¥œ¥Ÿ','ªÔ∞Ë≈¡','2019/09/09','2019/09/09',DEFAULT,DEFAULT,'¿ΩΩƒ ¿¸≈Î',DEFAULT,'T2');
INSERT INTO THEME_LIST VALUES(SEQ_TNO.NEXTVAL,DEFAULT,'TEST13','≈◊Ω∫∆Æ13¿‘¥œ¥Ÿ','∫“≤…≥Ó¿Ã','2019/04/04','2019/04/04',DEFAULT,DEFAULT,'√‡¡¶',DEFAULT,'T4');

INSERT INTO THEME_FILES VALUES(1,'cat.jpg','20200404.jpg');
INSERT INTO THEME_FILES VALUES(2,'dog.jpg','20191010.jpg');
INSERT INTO THEME_FILES VALUES(3,'a.jpg','20191111.jpg');
INSERT INTO THEME_FILES VALUES(4,'b.jpg','20191212.jpg');
INSERT INTO THEME_FILES VALUES(5,'c.jpg','20200101.jpg');
INSERT INTO THEME_FILES VALUES(6,'d.jpg','20200202.jpg');
INSERT INTO THEME_FILES VALUES(7,'e.jpg','20200303.jpg');
INSERT INTO THEME_FILES VALUES(8,'f.jpg','20190505.jpg');
INSERT INTO THEME_FILES VALUES(9,'g.jpg','20190606.jpg');
INSERT INTO THEME_FILES VALUES(10,'h.jpg','20190707.jpg');
INSERT INTO THEME_FILES VALUES(11,'i.jpg','20190808.jpg');
INSERT INTO THEME_FILES VALUES(12,'j.jpg','20190909.jpg');
INSERT INTO THEME_FILES VALUES(13,'k.jpg','20190404.jpg');
CREATE TABLE QNA(
	QID NUMBER PRIMARY KEY,
	QTITLE VARCHAR2(300) NOT NULL,
	QCONTENT VARCHAR2(3000) NOT NULL,
	QWRITER VARCHAR2(60), -- REFERENCES MEMBER ON DELETE CASCADE
	Q_CREATE_DATE DATE DEFAULT SYSDATE,
	Q_ANSWER_DATE DATE DEFAULT SYSDATE,
	Q_STATUS VARCHAR2(1) DEFAULT 'N' CHECK (Q_STATUS IN('Y','N','X'))
);


INSERT INTO QNA VALUES(SEQ_QID.NEXTVAL,'ÏãùÏÇ¨ÌïòÏÖ®Ïñ¥Ïöî?','ÏãùÏÇ¨ ÌïòÏÖ®ÎäîÏßÄ Í∂ÅÍ∏àÌï©ÎãàÎã§.','hyhihi',DEFAULT,NULL,DEFAULT);
INSERT INTO QNA VALUES(SEQ_QID.NEXTVAL,'ÌïúÍ∞ï Ï¢ãÏïÑÌïòÏÑ∏Ïöî?','ÌïúÍ∞ï Ïù¥ÏÅòÏßÄ ÏïäÏïÑÏöî?„Öé„Öé„Öé.','hooni',DEFAULT,NULL,DEFAULT);
INSERT INTO QNA VALUES(SEQ_QID.NEXTVAL,'ÏÑúÏö∏ÏóêÏÑú Ïñ¥Îîú Ï†úÏùº Ï¢ãÏïÑÌïòÏÑ∏Ïöî?','Ï†ÄÎäî ÌïúÍ∞ïÏù¥ Ï†úÏùº Ï¢ãÏïÑÏöî','mama',DEFAULT,NULL,DEFAULT);
COMMIT;