SET DEFINE OFF;
Insert into ALIGO.THEME_FILES (T_CODE_NUMBER,T_ORIGINAL_FILE,T_MODIFY_FILE) values (1,'http://english.visitseoul.net/comm/getImage?srvcId=MEDIA&amp;parentSn=26775&amp;fileTy=MEDIA&amp;fileNo=1','http://english.visitseoul.net/comm/getImage?srvcId=MEDIA&amp;parentSn=26775&amp;fileTy=MEDIA&amp;fileNo=1');
Insert into ALIGO.THEME_FILES (T_CODE_NUMBER,T_ORIGINAL_FILE,T_MODIFY_FILE) values (2,'http://english.visitseoul.net/comm/getImage?srvcId=MEDIA&amp;parentSn=21311&amp;fileTy=MEDIA&amp;fileNo=1&amp;thumbTy=L','http://english.visitseoul.net/comm/getImage?srvcId=MEDIA&amp;parentSn=21311&amp;fileTy=MEDIA&amp;fileNo=1&amp;thumbTy=L');
Insert into ALIGO.THEME_FILES (T_CODE_NUMBER,T_ORIGINAL_FILE,T_MODIFY_FILE) values (3,'http://www.visitseoul.net/comm/getImage?srvcId=MEDIA&amp;parentSn=28235&amp;fileTy=MEDIA&amp;fileNo=2','http://www.visitseoul.net/comm/getImage?srvcId=MEDIA&amp;parentSn=28235&amp;fileTy=MEDIA&amp;fileNo=2');
Insert into ALIGO.THEME_FILES (T_CODE_NUMBER,T_ORIGINAL_FILE,T_MODIFY_FILE) values (4,'http://english.visitseoul.net/comm/getImage?srvcId=MEDIA&amp;parentSn=26475&amp;fileTy=MEDIA&amp;fileNo=1','http://english.visitseoul.net/comm/getImage?srvcId=MEDIA&amp;parentSn=26475&amp;fileTy=MEDIA&amp;fileNo=1');
Insert into ALIGO.THEME_FILES (T_CODE_NUMBER,T_ORIGINAL_FILE,T_MODIFY_FILE) values (5,'http://english.visitseoul.net/comm/getImage?srvcId=MEDIA&amp;parentSn=24356&amp;fileTy=MEDIA&amp;fileNo=1','http://english.visitseoul.net/comm/getImage?srvcId=MEDIA&amp;parentSn=24356&amp;fileTy=MEDIA&amp;fileNo=1');
Insert into ALIGO.THEME_FILES (T_CODE_NUMBER,T_ORIGINAL_FILE,T_MODIFY_FILE) values (6,'http://english.visitseoul.net/comm/getImage?srvcId=MEDIA&amp;parentSn=26969&amp;fileTy=MEDIA&amp;fileNo=1','http://english.visitseoul.net/comm/getImage?srvcId=MEDIA&amp;parentSn=26969&amp;fileTy=MEDIA&amp;fileNo=1');
Insert into ALIGO.THEME_FILES (T_CODE_NUMBER,T_ORIGINAL_FILE,T_MODIFY_FILE) values (7,'http://english.visitseoul.net/comm/getImage?srvcId=MEDIA&amp;parentSn=17144&amp;fileTy=MEDIA&amp;fileNo=1&amp;thumbTy=L','http://english.visitseoul.net/comm/getImage?srvcId=MEDIA&amp;parentSn=17144&amp;fileTy=MEDIA&amp;fileNo=1&amp;thumbTy=L');

